### ISSUE TITLE
在Overleaf中无法完整通过编译

### ISSUE THREAD

**Issue by sparkcyf** [tuna/thulib-latex-talk#12]
## 1
将本Repo的 [release 2021.11](https://github.com/tuna/thulib-latex-talk/releases/tag/2020.11) 上传至Overleaf，对文件不做修改，使用XeLaTeX编译，出现以下错误：

```
/compile/latex-talk.tex:95: Package fontspec Error: The font "Source Han Sans S
C" cannot be found.
```
---
## 2
尝试注释 Source Han Sans 和 FontsAwesome 的相关宏包（`\usepackage{fontawesome} \setCJKsansfont{Source Han Sans SC} \setCJKmonofont{Source Han Sans SC}`）并尝试再次编译，出现以下错误（204行是beamer第2页的结尾位置）（ https://github.com/tuna/thulib-latex-talk/blob/ce61578cadd5bffaaf7091042cd450db7435cc9c/introduction.tex#L203 ）：
```
/compile/latex-talk.tex:204: Undefined control sequence.
<argument> \faLink 
                   
l.204 \end{frame}
```
此时，Overleaf仅输出了Beamer的第一页PDF，并提示了以下的警告：
![image](https://user-images.githubusercontent.com/14960340/110813143-2ec79f00-82c3-11eb-9abe-1d4bb15c364a.png)

![image](https://user-images.githubusercontent.com/14960340/110812875-f1631180-82c2-11eb-8fed-f4c07debf952.png)
---
## 3
尝试删除第2页（关于）的文本后，再次尝试编译。Overleaf一直输出到了`introduction.tex`中的“下载”这一页（文档的15页）

输出PDF： [尝试3.pdf](https://github.com/tuna/thulib-latex-talk/files/6124172/3.pdf)

此时的报错为（应该是这一行 https://github.com/tuna/thulib-latex-talk/blob/ce61578cadd5bffaaf7091042cd450db7435cc9c/introduction.tex#L273 ）：
```
(/compile/output.vrb
/compile/output.vrb:10: Undefined control sequence.
<argument> \faLink 
                   
l.10 ...edu.cn/CTAN/systems/mac/mactex/MacTeX.pkg}
```
---
## 4
将 introduction.tex 的“安装”Beamer （ https://github.com/tuna/thulib-latex-talk/blob/ce61578cadd5bffaaf7091042cd450db7435cc9c/introduction.tex#L205 ）注释后，编译会卡在
```
/compile/output.vrb:13: Undefined control sequence.
<argument> \faLink 
                   
l.13 .../www.tug.org/texlive/debian.html\#vanilla}
```
https://github.com/tuna/thulib-latex-talk/blob/ce61578cadd5bffaaf7091042cd450db7435cc9c/introduction.tex#L322

![image](https://user-images.githubusercontent.com/14960340/110815635-941c8f80-82c5-11eb-8157-220d56178c1e.png)

---
(暂时没有进行进一步的测试，不过每次出错的错误类型均为`Undefined control sequence.`，本人也暂时无法从log中找出错误的原因。）

**Comment by Harry-Chen** [comment]
目前将 `fontset` 改成 `fandol` 即可在 Overleaf 编译

**Comment by PengchengAi** [comment]
Win 10，TeX Live 2020，vscode + LaTex Workshop，修改以下后编译通过：
line 4: fontset=ubuntu -> fontset=fandol
line 94: \setCJKsansfont{Noto Sans CJK SC} -> \setCJKsansfont{SimHei}
line 95: \setCJKmonofont{Noto Sans Mono CJK SC} -> \setCJKmonofont{STFangsong}

**Comment by Harry-Chen** [comment]
是的，就是字体问题
