### ISSUE TITLE
设置了never auto build，但是失效了

### ISSUE THREAD

**Issue by real-bird-kun** [tuna/thulib-latex-talk#14]
我不想vscode 每次在我保存文件的时候就开始build，所以设置了auto build为never。
但是好像这个命令没有作用。在我用:w的vim命令保存tex文件时，依然会build。

我的环境是： vscode 1.65 + vim 1.22.2 + latexshop 8.23.0

谢谢大家的帮助！

**Comment by guanzd88** [comment]
小黑子开庭带上你的论文
