### ISSUE TITLE
“bst 参考文献样式文件”已经不叫 thubib.bst 了

### ISSUE THREAD

**Issue by zepinglee** [tuna/thulib-latex-talk#2]
现在是 thuthesis-author-year.bst 和 thuthesis-numeric.bst，建议介绍一下两种参考文献风格怎么调用

**Comment by zepinglee** [comment]
citation 的样式应该是“[12-13]”不是“[12, 13]”

**Comment by alick** [comment]
楼主能 PR 么？多谢

**Comment by alick** [comment]
#8 作了更新。但限于篇幅，这里就不具体介绍多种 bst 的使用了
