### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by xiekuncn** [tuna/thulib-latex-talk#3]
我对Latex非常陌生，很感谢您提供了非常好的模板工程，帮我学习如何使用该工具。
但是使用最新的版本，有提示ctexbeamer.cls not found。请问，我在哪里可以获取该文件呢？

我切换到了Tag 1.0的版本，也有一些提示pdf找不到的bug，不过可以skip掉。

使用环境是
```
OS: Windows 7
XeLatex version: MiKTeX-XeTeX 2.9.4308 (0.9997.5) (MiKTeX 2.9)
Ctex: version: ctex 0.2.14 ($Date: 2010/01/22 06:07:06 $)
```

**Comment by alick** [comment]
您的 tex 套件 (MikTeX) 可能过时了，里面带的 ctex 版本过低。建议更新 miktex，并使用其附带的 tex 包管理器升级 tex
宏包。

作为参考，我这里的 ctex 版本是 2.4.14 2018/05/02.

**Comment by alick** [comment]
关闭了。如更新后仍有问题请重开。
