### ISSUE TITLE
封面页添加副标题选项

### ISSUE THREAD

**Issue by alulujasmine** [tuna/thulib-latex-talk#4]
可在此行 https://github.com/tuna/thulib-latex-talk/blob/master/beamerinnerthemematerial.sty#L26
后添加一行{\usebeamerfont{subtitle} \insertsubtitle}，即可在 https://github.com/tuna/thulib-latex-talk/blob/master/latex-talk.tex 中使用\subtitle{} 在主标题下方添加副标题。

**Comment by alick** [comment]
如果可以，请把修改做成 Pull Request

**Comment by alick** [comment]
Fixed by #5
