### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by fancyerii** [tuna/thulib-latex-talk#6]
定位错误是\end{frame}这一行：
\begin{frame}
  \titlepage
\end{frame}

错误信息是：
! LaTeX Error: There's no line here to end.

**Comment by alick** [comment]
有对文件做修改吗？比如删除了幻灯片标题。

麻烦告知下编译环境。tex 套件版本(miktex 2.9?) Xelatex?

**Comment by moetayuko** [comment]
Revert https://github.com/tuna/thulib-latex-talk/commit/32a1c8fce158f11e36c1ac2fdb43523f0b20e92d 或在`latex-talk.tex`添加subtitle即可

**Comment by alick** [comment]
感谢 @dianlujitao ，修正已提交 PR #7

**Comment by Harry-Chen** [comment]
Thanks, fixed.
